# Generated by Django 2.1 on 2019-01-24 13:18

from __future__ import unicode_literals

from django.db import migrations, models
from django.contrib.auth.models import User

def addDefaultUser(apps, schema_editor):

    user = User.objects.create_user(username='admin',
                                     email='admin@admin.com',
                                     password='admin')

class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(addDefaultUser),
    ]